services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_URL=http://finance-service:8080/api/v1
    container_name: finance-frontend
    ports:
      - "80:80"
    environment:
      - API_URL=http://finance-service:8080/api/v1
    networks:
      - finance-network
    restart: unless-stopped

networks:
  finance-network:
    external: true
